"""Freeze the settings exposed by our pinned Windows engine, without running it."""
import argparse
import json
import re
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument("config", type=Path, help="Config generated by the pinned upstream build")
args = parser.parse_args()
text = args.config.read_text(encoding="utf-8-sig")
parsed = tomllib.loads(text)
types = {}
for source in (ROOT / "engine/xenia/src/xenia").rglob("*.cc"):
    for typ, name in re.findall(r"DEFINE_(bool|int32|uint32|int64|uint64|double|float|string|path)\s*\(\s*(\w+)\s*,", source.read_text(encoding="utf-8", errors="replace")):
        types[name] = typ

groups = {"APU": "audio", "CPU": "cpu", "Content": "system", "D3D12": "graphics",
          "Display": "display", "GPU": "graphics", "GPU.Debug": "advanced", "General": "general",
          "HID": "input", "HID.Key": "keyboard", "Kernel": "system", "Logging": "logging",
          "Memory": "cpu", "Profiles": "profiles", "SDL": "input", "Storage": "storage",
          "UI": "overlay", "Video": "display", "Vulkan": "graphics", "Win32": "cpu", "x64": "cpu", "Config": "advanced"}
entries = []
section = ""
for line in text.splitlines():
    match = re.match(r"\[([\w.]+)\]", line)
    if match:
        section = match[1]
        continue
    match = re.match(r"(\w+)\s*=.*", line)
    if match:
        name = match[1]
        table = parsed
        for part in section.split("."):
            table = table[part]
        typ = "string" if section == "HID.Key" else types.get(name)
        if not typ:
            raise ValueError(f"Type missing for {section}.{name}")
        value = table[name]
        if typ in ("int32", "uint32", "int64", "uint64", "float", "double"):
            value = str(value)
        entries.append(dict(key=f"{section}.{name}", name=name, section=section,
                            group=groups[section], type=typ, default=value,
                            description=line.split("#", 1)[1].strip() if "#" in line else ""))
    elif line.lstrip().startswith("#") and entries:
        entries[-1]["description"] += "\n" + line.split("#", 1)[1].strip()

overrides = json.loads((ROOT / "app/settings-labels.json").read_text(encoding="utf-8"))
for entry in entries:
    entry.update(overrides.get(entry["name"], {}))
    entry.setdefault("label", entry["name"].replace("_", " "))
    entry.setdefault("help", "")
    entry["readonly"] = entry["name"] == "defaults_date"
    if "choices" not in entry and entry["type"] == "string":
        choices = re.search(r"Use: \[([^\]]+)\]", entry["description"])
        if choices:
            values = [x.strip() for x in choices[1].split(",")]
            if entry["default"] not in values:
                values.insert(0, entry["default"])
            entry["choices"] = [dict(label=v or "Automático", value=v) for v in values]

dialog = (ROOT / "engine/xenia/src/xenia/app/console_settings_dialog.cc").read_text(encoding="utf-8")
countries_text = dialog.split("kCountryMap = {")[1].split("};")[0]
countries = [dict(value=v, label=code) for v, code in re.findall(r'\{(\d+),\s*"([A-Z]+)"\}', countries_text)]
common = ["gpu", "draw_resolution_scale_x", "draw_resolution_scale_y", "vsync",
          "d3d12_adapter", "vulkan_device", "render_target_path", "fullscreen",
          "window_size_x", "window_size_y", "apu", "mute", "hid", "language",
          "logged_profile_slot_0_xuid", "logged_profile_slot_1_xuid",
          "logged_profile_slot_2_xuid", "logged_profile_slot_3_xuid"]
for entry in entries:
    if any(word in entry["name"] for word in ("break_on_", "validation", "debug_dump")):
        entry["group"] = "advanced"
entries.sort(key=lambda item: (common.index(item["name"]) if item["name"] in common else len(common), item["key"]))
catalog = dict(revision="6f9840568bb7dc9f5a9adb94801a99b18a7b2a60", entries=entries, countries=countries)
output = ROOT / "app/settings-catalog.json"
output.write_text(json.dumps(catalog, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(f"{len(entries)} settings written to {output}")
